// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.0
// source: consensus/polybft/proto/polybft.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type BridgeCallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index uint64 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *BridgeCallRequest) Reset() {
	*x = BridgeCallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consensus_polybft_proto_polybft_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BridgeCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeCallRequest) ProtoMessage() {}

func (x *BridgeCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_polybft_proto_polybft_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeCallRequest.ProtoReflect.Descriptor instead.
func (*BridgeCallRequest) Descriptor() ([]byte, []int) {
	return file_consensus_polybft_proto_polybft_proto_rawDescGZIP(), []int{0}
}

func (x *BridgeCallRequest) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

type BridgeCallResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateSync *StateSync `protobuf:"bytes,1,opt,name=stateSync,proto3" json:"stateSync,omitempty"`
	Data      string     `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BridgeCallResponse) Reset() {
	*x = BridgeCallResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consensus_polybft_proto_polybft_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BridgeCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeCallResponse) ProtoMessage() {}

func (x *BridgeCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_polybft_proto_polybft_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeCallResponse.ProtoReflect.Descriptor instead.
func (*BridgeCallResponse) Descriptor() ([]byte, []int) {
	return file_consensus_polybft_proto_polybft_proto_rawDescGZIP(), []int{1}
}

func (x *BridgeCallResponse) GetStateSync() *StateSync {
	if x != nil {
		return x.StateSync
	}
	return nil
}

func (x *BridgeCallResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type ConsensusSnapshotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConsensusSnapshotRequest) Reset() {
	*x = ConsensusSnapshotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consensus_polybft_proto_polybft_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsensusSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusSnapshotRequest) ProtoMessage() {}

func (x *ConsensusSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_polybft_proto_polybft_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusSnapshotRequest.ProtoReflect.Descriptor instead.
func (*ConsensusSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_consensus_polybft_proto_polybft_proto_rawDescGZIP(), []int{2}
}

type ConsensusSnapshotResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockNumber uint64       `protobuf:"varint,1,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	Validators  []*Validator `protobuf:"bytes,2,rep,name=validators,proto3" json:"validators,omitempty"`
}

func (x *ConsensusSnapshotResponse) Reset() {
	*x = ConsensusSnapshotResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consensus_polybft_proto_polybft_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsensusSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusSnapshotResponse) ProtoMessage() {}

func (x *ConsensusSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_polybft_proto_polybft_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusSnapshotResponse.ProtoReflect.Descriptor instead.
func (*ConsensusSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_consensus_polybft_proto_polybft_proto_rawDescGZIP(), []int{3}
}

func (x *ConsensusSnapshotResponse) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *ConsensusSnapshotResponse) GetValidators() []*Validator {
	if x != nil {
		return x.Validators
	}
	return nil
}

type Validator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address     string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	VotingPower uint64 `protobuf:"varint,2,opt,name=votingPower,proto3" json:"votingPower,omitempty"`
}

func (x *Validator) Reset() {
	*x = Validator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consensus_polybft_proto_polybft_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Validator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Validator) ProtoMessage() {}

func (x *Validator) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_polybft_proto_polybft_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Validator.ProtoReflect.Descriptor instead.
func (*Validator) Descriptor() ([]byte, []int) {
	return file_consensus_polybft_proto_polybft_proto_rawDescGZIP(), []int{4}
}

func (x *Validator) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Validator) GetVotingPower() uint64 {
	if x != nil {
		return x.VotingPower
	}
	return 0
}

type BridgeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BridgeRequest) Reset() {
	*x = BridgeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consensus_polybft_proto_polybft_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BridgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeRequest) ProtoMessage() {}

func (x *BridgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_polybft_proto_polybft_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeRequest.ProtoReflect.Descriptor instead.
func (*BridgeRequest) Descriptor() ([]byte, []int) {
	return file_consensus_polybft_proto_polybft_proto_rawDescGZIP(), []int{5}
}

type BridgeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateSyncs         []*StateSync `protobuf:"bytes,1,rep,name=stateSyncs,proto3" json:"stateSyncs,omitempty"`
	Epoch              uint64       `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	NextCommittedIndex uint64       `protobuf:"varint,3,opt,name=nextCommittedIndex,proto3" json:"nextCommittedIndex,omitempty"`
	NextExecutionIndex uint64       `protobuf:"varint,4,opt,name=nextExecutionIndex,proto3" json:"nextExecutionIndex,omitempty"`
	LastCommittedIndex uint64       `protobuf:"varint,5,opt,name=lastCommittedIndex,proto3" json:"lastCommittedIndex,omitempty"`
}

func (x *BridgeResponse) Reset() {
	*x = BridgeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consensus_polybft_proto_polybft_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BridgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeResponse) ProtoMessage() {}

func (x *BridgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_polybft_proto_polybft_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeResponse.ProtoReflect.Descriptor instead.
func (*BridgeResponse) Descriptor() ([]byte, []int) {
	return file_consensus_polybft_proto_polybft_proto_rawDescGZIP(), []int{6}
}

func (x *BridgeResponse) GetStateSyncs() []*StateSync {
	if x != nil {
		return x.StateSyncs
	}
	return nil
}

func (x *BridgeResponse) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *BridgeResponse) GetNextCommittedIndex() uint64 {
	if x != nil {
		return x.NextCommittedIndex
	}
	return 0
}

func (x *BridgeResponse) GetNextExecutionIndex() uint64 {
	if x != nil {
		return x.NextExecutionIndex
	}
	return 0
}

func (x *BridgeResponse) GetLastCommittedIndex() uint64 {
	if x != nil {
		return x.LastCommittedIndex
	}
	return 0
}

type StateSync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sender string `protobuf:"bytes,6,opt,name=sender,proto3" json:"sender,omitempty"`
	Target string `protobuf:"bytes,7,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *StateSync) Reset() {
	*x = StateSync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consensus_polybft_proto_polybft_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSync) ProtoMessage() {}

func (x *StateSync) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_polybft_proto_polybft_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateSync.ProtoReflect.Descriptor instead.
func (*StateSync) Descriptor() ([]byte, []int) {
	return file_consensus_polybft_proto_polybft_proto_rawDescGZIP(), []int{7}
}

func (x *StateSync) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StateSync) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *StateSync) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

var File_consensus_polybft_proto_polybft_proto protoreflect.FileDescriptor

var file_consensus_polybft_proto_polybft_proto_rawDesc = []byte{
	0x0a, 0x25, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x2f, 0x70, 0x6f, 0x6c, 0x79,
	0x62, 0x66, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x6c, 0x79, 0x62, 0x66,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29,
	0x0a, 0x11, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x58, 0x0a, 0x12, 0x42, 0x72, 0x69,
	0x64, 0x67, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2e, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x53, 0x79, 0x6e, 0x63, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x53, 0x79, 0x6e, 0x63, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x53, 0x79, 0x6e, 0x63, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x1a, 0x0a, 0x18, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73,
	0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x6f, 0x0a, 0x19, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x53, 0x6e, 0x61, 0x70,
	0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x30,
	0x0a, 0x0a, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x6f, 0x72, 0x52, 0x0a, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73,
	0x22, 0x47, 0x0a, 0x09, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x76, 0x6f, 0x74, 0x69, 0x6e,
	0x67, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x76, 0x6f,
	0x74, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x22, 0x0f, 0x0a, 0x0d, 0x42, 0x72, 0x69,
	0x64, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xe8, 0x01, 0x0a, 0x0e, 0x42,
	0x72, 0x69, 0x64, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a,
	0x0a, 0x73, 0x74, 0x61, 0x74, 0x65, 0x53, 0x79, 0x6e, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x53,
	0x79, 0x6e, 0x63, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x65, 0x53, 0x79, 0x6e, 0x63, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x65, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x2e, 0x0a, 0x12, 0x6e, 0x65, 0x78, 0x74, 0x43, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x12, 0x6e, 0x65, 0x78, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x2e, 0x0a, 0x12, 0x6e, 0x65, 0x78, 0x74, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x12, 0x6e, 0x65, 0x78, 0x74, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x2e, 0x0a, 0x12, 0x6c, 0x61, 0x73, 0x74, 0x43, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x12, 0x6c, 0x61, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x4b, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x74, 0x65, 0x53, 0x79,
	0x6e, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x32, 0xdb, 0x01, 0x0a, 0x07, 0x50, 0x6f, 0x6c, 0x79, 0x62, 0x66, 0x74, 0x12, 0x56,
	0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x53, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x73,
	0x65, 0x6e, 0x73, 0x75, 0x73, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6e,
	0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65,
	0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42,
	0x72, 0x69, 0x64, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a,
	0x0a, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x18, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x72,
	0x69, 0x64, 0x67, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x1a, 0x5a, 0x18, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x2f, 0x70,
	0x6f, 0x6c, 0x79, 0x62, 0x66, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_consensus_polybft_proto_polybft_proto_rawDescOnce sync.Once
	file_consensus_polybft_proto_polybft_proto_rawDescData = file_consensus_polybft_proto_polybft_proto_rawDesc
)

func file_consensus_polybft_proto_polybft_proto_rawDescGZIP() []byte {
	file_consensus_polybft_proto_polybft_proto_rawDescOnce.Do(func() {
		file_consensus_polybft_proto_polybft_proto_rawDescData = protoimpl.X.CompressGZIP(file_consensus_polybft_proto_polybft_proto_rawDescData)
	})
	return file_consensus_polybft_proto_polybft_proto_rawDescData
}

var file_consensus_polybft_proto_polybft_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_consensus_polybft_proto_polybft_proto_goTypes = []interface{}{
	(*BridgeCallRequest)(nil),         // 0: proto.BridgeCallRequest
	(*BridgeCallResponse)(nil),        // 1: proto.BridgeCallResponse
	(*ConsensusSnapshotRequest)(nil),  // 2: proto.ConsensusSnapshotRequest
	(*ConsensusSnapshotResponse)(nil), // 3: proto.ConsensusSnapshotResponse
	(*Validator)(nil),                 // 4: proto.Validator
	(*BridgeRequest)(nil),             // 5: proto.BridgeRequest
	(*BridgeResponse)(nil),            // 6: proto.BridgeResponse
	(*StateSync)(nil),                 // 7: proto.StateSync
}
var file_consensus_polybft_proto_polybft_proto_depIdxs = []int32{
	7, // 0: proto.BridgeCallResponse.stateSync:type_name -> proto.StateSync
	4, // 1: proto.ConsensusSnapshotResponse.validators:type_name -> proto.Validator
	7, // 2: proto.BridgeResponse.stateSyncs:type_name -> proto.StateSync
	2, // 3: proto.Polybft.ConsensusSnapshot:input_type -> proto.ConsensusSnapshotRequest
	5, // 4: proto.Polybft.Bridge:input_type -> proto.BridgeRequest
	0, // 5: proto.Polybft.BridgeCall:input_type -> proto.BridgeCallRequest
	3, // 6: proto.Polybft.ConsensusSnapshot:output_type -> proto.ConsensusSnapshotResponse
	6, // 7: proto.Polybft.Bridge:output_type -> proto.BridgeResponse
	1, // 8: proto.Polybft.BridgeCall:output_type -> proto.BridgeCallResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_consensus_polybft_proto_polybft_proto_init() }
func file_consensus_polybft_proto_polybft_proto_init() {
	if File_consensus_polybft_proto_polybft_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_consensus_polybft_proto_polybft_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BridgeCallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_consensus_polybft_proto_polybft_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BridgeCallResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_consensus_polybft_proto_polybft_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsensusSnapshotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_consensus_polybft_proto_polybft_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsensusSnapshotResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_consensus_polybft_proto_polybft_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Validator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_consensus_polybft_proto_polybft_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BridgeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_consensus_polybft_proto_polybft_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BridgeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_consensus_polybft_proto_polybft_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateSync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_consensus_polybft_proto_polybft_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_consensus_polybft_proto_polybft_proto_goTypes,
		DependencyIndexes: file_consensus_polybft_proto_polybft_proto_depIdxs,
		MessageInfos:      file_consensus_polybft_proto_polybft_proto_msgTypes,
	}.Build()
	File_consensus_polybft_proto_polybft_proto = out.File
	file_consensus_polybft_proto_polybft_proto_rawDesc = nil
	file_consensus_polybft_proto_polybft_proto_goTypes = nil
	file_consensus_polybft_proto_polybft_proto_depIdxs = nil
}
