FROM alpine:3.14

RUN set -x \
    && apk add --update --no-cache \
       ca-certificates \
    && rm -rf /var/cache/apk/*
COPY blade /usr/local/bin/

EXPOSE 8545 9632 1478

RUN addgroup -S blade-group \
    && adduser -S blade -G blade-group

USER blade

ENTRYPOINT ["blade"]
