// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// IbftClient is the client API for Ibft service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IbftClient interface {
	PublishSignedMessage(ctx context.Context, in *SignedMessage, opts ...grpc.CallOption) (*empty.Empty, error)
}

type ibftClient struct {
	cc grpc.ClientConnInterface
}

func NewIbftClient(cc grpc.ClientConnInterface) IbftClient {
	return &ibftClient{cc}
}

func (c *ibftClient) PublishSignedMessage(ctx context.Context, in *SignedMessage, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/v1.Ibft/PublishSignedMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IbftServer is the server API for Ibft service.
// All implementations must embed UnimplementedIbftServer
// for forward compatibility
type IbftServer interface {
	PublishSignedMessage(context.Context, *SignedMessage) (*empty.Empty, error)
	mustEmbedUnimplementedIbftServer()
}

// UnimplementedIbftServer must be embedded to have forward compatible implementations.
type UnimplementedIbftServer struct {
}

func (UnimplementedIbftServer) PublishSignedMessage(context.Context, *SignedMessage) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishSignedMessage not implemented")
}
func (UnimplementedIbftServer) mustEmbedUnimplementedIbftServer() {}

// UnsafeIbftServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IbftServer will
// result in compilation errors.
type UnsafeIbftServer interface {
	mustEmbedUnimplementedIbftServer()
}

func RegisterIbftServer(s grpc.ServiceRegistrar, srv IbftServer) {
	s.RegisterService(&_Ibft_serviceDesc, srv)
}

func _Ibft_PublishSignedMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignedMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IbftServer).PublishSignedMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Ibft/PublishSignedMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IbftServer).PublishSignedMessage(ctx, req.(*SignedMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ibft_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Ibft",
	HandlerType: (*IbftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishSignedMessage",
			Handler:    _Ibft_PublishSignedMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bridge/sam/proto/sam.proto",
}
