// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.0
// source: txpool/proto/operator.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AddTxnReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Raw  *any.Any `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	From string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
}

func (x *AddTxnReq) Reset() {
	*x = AddTxnReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txpool_proto_operator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTxnReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTxnReq) ProtoMessage() {}

func (x *AddTxnReq) ProtoReflect() protoreflect.Message {
	mi := &file_txpool_proto_operator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTxnReq.ProtoReflect.Descriptor instead.
func (*AddTxnReq) Descriptor() ([]byte, []int) {
	return file_txpool_proto_operator_proto_rawDescGZIP(), []int{0}
}

func (x *AddTxnReq) GetRaw() *any.Any {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *AddTxnReq) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

type TxnPoolStatusResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Length uint64 `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
}

func (x *TxnPoolStatusResp) Reset() {
	*x = TxnPoolStatusResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txpool_proto_operator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxnPoolStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnPoolStatusResp) ProtoMessage() {}

func (x *TxnPoolStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_txpool_proto_operator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnPoolStatusResp.ProtoReflect.Descriptor instead.
func (*TxnPoolStatusResp) Descriptor() ([]byte, []int) {
	return file_txpool_proto_operator_proto_rawDescGZIP(), []int{1}
}

func (x *TxnPoolStatusResp) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type TxPoolEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TxPoolEvent) Reset() {
	*x = TxPoolEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_txpool_proto_operator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxPoolEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxPoolEvent) ProtoMessage() {}

func (x *TxPoolEvent) ProtoReflect() protoreflect.Message {
	mi := &file_txpool_proto_operator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxPoolEvent.ProtoReflect.Descriptor instead.
func (*TxPoolEvent) Descriptor() ([]byte, []int) {
	return file_txpool_proto_operator_proto_rawDescGZIP(), []int{2}
}

var File_txpool_proto_operator_proto protoreflect.FileDescriptor

var file_txpool_proto_operator_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x74, 0x78, 0x70, 0x6f, 0x6f, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76,
	0x31, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x47, 0x0a, 0x09, 0x41, 0x64, 0x64,
	0x54, 0x78, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x26, 0x0a, 0x03, 0x72, 0x61, 0x77, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x03, 0x72, 0x61, 0x77, 0x12, 0x12,
	0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72,
	0x6f, 0x6d, 0x22, 0x2b, 0x0a, 0x11, 0x54, 0x78, 0x6e, 0x50, 0x6f, 0x6f, 0x6c, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22,
	0x0d, 0x0a, 0x0b, 0x54, 0x78, 0x50, 0x6f, 0x6f, 0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x32, 0xb3,
	0x01, 0x0a, 0x0f, 0x54, 0x78, 0x6e, 0x50, 0x6f, 0x6f, 0x6c, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x12, 0x37, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x15, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x78, 0x6e, 0x50, 0x6f, 0x6f,
	0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2f, 0x0a, 0x06, 0x41,
	0x64, 0x64, 0x54, 0x78, 0x6e, 0x12, 0x0d, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x78,
	0x6e, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x36, 0x0a, 0x09,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x0f, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x78, 0x50, 0x6f, 0x6f, 0x6c, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x30, 0x01, 0x42, 0x0f, 0x5a, 0x0d, 0x2f, 0x74, 0x78, 0x70, 0x6f, 0x6f, 0x6c, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_txpool_proto_operator_proto_rawDescOnce sync.Once
	file_txpool_proto_operator_proto_rawDescData = file_txpool_proto_operator_proto_rawDesc
)

func file_txpool_proto_operator_proto_rawDescGZIP() []byte {
	file_txpool_proto_operator_proto_rawDescOnce.Do(func() {
		file_txpool_proto_operator_proto_rawDescData = protoimpl.X.CompressGZIP(file_txpool_proto_operator_proto_rawDescData)
	})
	return file_txpool_proto_operator_proto_rawDescData
}

var file_txpool_proto_operator_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_txpool_proto_operator_proto_goTypes = []interface{}{
	(*AddTxnReq)(nil),         // 0: v1.AddTxnReq
	(*TxnPoolStatusResp)(nil), // 1: v1.TxnPoolStatusResp
	(*TxPoolEvent)(nil),       // 2: v1.TxPoolEvent
	(*any.Any)(nil),           // 3: google.protobuf.Any
	(*empty.Empty)(nil),       // 4: google.protobuf.Empty
}
var file_txpool_proto_operator_proto_depIdxs = []int32{
	3, // 0: v1.AddTxnReq.raw:type_name -> google.protobuf.Any
	4, // 1: v1.TxnPoolOperator.Status:input_type -> google.protobuf.Empty
	0, // 2: v1.TxnPoolOperator.AddTxn:input_type -> v1.AddTxnReq
	4, // 3: v1.TxnPoolOperator.Subscribe:input_type -> google.protobuf.Empty
	1, // 4: v1.TxnPoolOperator.Status:output_type -> v1.TxnPoolStatusResp
	4, // 5: v1.TxnPoolOperator.AddTxn:output_type -> google.protobuf.Empty
	2, // 6: v1.TxnPoolOperator.Subscribe:output_type -> v1.TxPoolEvent
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_txpool_proto_operator_proto_init() }
func file_txpool_proto_operator_proto_init() {
	if File_txpool_proto_operator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_txpool_proto_operator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTxnReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_txpool_proto_operator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxnPoolStatusResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_txpool_proto_operator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxPoolEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_txpool_proto_operator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_txpool_proto_operator_proto_goTypes,
		DependencyIndexes: file_txpool_proto_operator_proto_depIdxs,
		MessageInfos:      file_txpool_proto_operator_proto_msgTypes,
	}.Build()
	File_txpool_proto_operator_proto = out.File
	file_txpool_proto_operator_proto_rawDesc = nil
	file_txpool_proto_operator_proto_goTypes = nil
	file_txpool_proto_operator_proto_depIdxs = nil
}
