// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.0
// source: network/proto/test/test.proto

package test

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *AReq) Reset() {
	*x = AReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_network_proto_test_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AReq) ProtoMessage() {}

func (x *AReq) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_test_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AReq.ProtoReflect.Descriptor instead.
func (*AReq) Descriptor() ([]byte, []int) {
	return file_network_proto_test_test_proto_rawDescGZIP(), []int{0}
}

func (x *AReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type AResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *AResp) Reset() {
	*x = AResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_network_proto_test_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AResp) ProtoMessage() {}

func (x *AResp) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_test_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AResp.ProtoReflect.Descriptor instead.
func (*AResp) Descriptor() ([]byte, []int) {
	return file_network_proto_test_test_proto_rawDescGZIP(), []int{1}
}

func (x *AResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_network_proto_test_test_proto protoreflect.FileDescriptor

var file_network_proto_test_test_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x74, 0x65, 0x73, 0x74, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x76, 0x31, 0x22, 0x18, 0x0a, 0x04, 0x41, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x19, 0x0a,
	0x05, 0x41, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x20, 0x0a, 0x04, 0x54, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x01, 0x41, 0x12, 0x08, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x52, 0x65, 0x71, 0x1a,
	0x09, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x52, 0x65, 0x73, 0x70, 0x42, 0x15, 0x5a, 0x13, 0x2f, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x73,
	0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_network_proto_test_test_proto_rawDescOnce sync.Once
	file_network_proto_test_test_proto_rawDescData = file_network_proto_test_test_proto_rawDesc
)

func file_network_proto_test_test_proto_rawDescGZIP() []byte {
	file_network_proto_test_test_proto_rawDescOnce.Do(func() {
		file_network_proto_test_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_network_proto_test_test_proto_rawDescData)
	})
	return file_network_proto_test_test_proto_rawDescData
}

var file_network_proto_test_test_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_network_proto_test_test_proto_goTypes = []interface{}{
	(*AReq)(nil),  // 0: v1.AReq
	(*AResp)(nil), // 1: v1.AResp
}
var file_network_proto_test_test_proto_depIdxs = []int32{
	0, // 0: v1.Test.A:input_type -> v1.AReq
	1, // 1: v1.Test.A:output_type -> v1.AResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_network_proto_test_test_proto_init() }
func file_network_proto_test_test_proto_init() {
	if File_network_proto_test_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_network_proto_test_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_network_proto_test_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_network_proto_test_test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_network_proto_test_test_proto_goTypes,
		DependencyIndexes: file_network_proto_test_test_proto_depIdxs,
		MessageInfos:      file_network_proto_test_test_proto_msgTypes,
	}.Build()
	File_network_proto_test_test_proto = out.File
	file_network_proto_test_test_proto_rawDesc = nil
	file_network_proto_test_test_proto_goTypes = nil
	file_network_proto_test_test_proto_depIdxs = nil
}
