// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// SyncerClient is the client API for Syncer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SyncerClient interface {
	GetBlocks(ctx context.Context, in *GetBlocksRequest, opts ...grpc.CallOption) (Syncer_GetBlocksClient, error)
	GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*Block, error)
	GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Status, error)
	NotifyStatus(ctx context.Context, in *Status, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type syncerClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncerClient(cc grpc.ClientConnInterface) SyncerClient {
	return &syncerClient{cc}
}

func (c *syncerClient) GetBlocks(ctx context.Context, in *GetBlocksRequest, opts ...grpc.CallOption) (Syncer_GetBlocksClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Syncer_serviceDesc.Streams[0], "/v1.Syncer/GetBlocks", opts...)
	if err != nil {
		return nil, err
	}
	x := &syncerGetBlocksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Syncer_GetBlocksClient interface {
	Recv() (*Block, error)
	grpc.ClientStream
}

type syncerGetBlocksClient struct {
	grpc.ClientStream
}

func (x *syncerGetBlocksClient) Recv() (*Block, error) {
	m := new(Block)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *syncerClient) GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*Block, error) {
	out := new(Block)
	err := c.cc.Invoke(ctx, "/v1.Syncer/GetBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncerClient) GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/v1.Syncer/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncerClient) NotifyStatus(ctx context.Context, in *Status, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/v1.Syncer/NotifyStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncerServer is the server API for Syncer service.
// All implementations must embed UnimplementedSyncerServer
// for forward compatibility
type SyncerServer interface {
	GetBlocks(*GetBlocksRequest, Syncer_GetBlocksServer) error
	GetBlock(context.Context, *GetBlockRequest) (*Block, error)
	GetStatus(context.Context, *emptypb.Empty) (*Status, error)
	NotifyStatus(context.Context, *Status) (*emptypb.Empty, error)
	mustEmbedUnimplementedSyncerServer()
}

// UnimplementedSyncerServer must be embedded to have forward compatible implementations.
type UnimplementedSyncerServer struct {
}

func (UnimplementedSyncerServer) GetBlocks(*GetBlocksRequest, Syncer_GetBlocksServer) error {
	return status.Errorf(codes.Unimplemented, "method GetBlocks not implemented")
}
func (UnimplementedSyncerServer) GetBlock(context.Context, *GetBlockRequest) (*Block, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlock not implemented")
}
func (UnimplementedSyncerServer) GetStatus(context.Context, *emptypb.Empty) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedSyncerServer) NotifyStatus(context.Context, *Status) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyStatus not implemented")
}
func (UnimplementedSyncerServer) mustEmbedUnimplementedSyncerServer() {}

// UnsafeSyncerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncerServer will
// result in compilation errors.
type UnsafeSyncerServer interface {
	mustEmbedUnimplementedSyncerServer()
}

func RegisterSyncerServer(s grpc.ServiceRegistrar, srv SyncerServer) {
	s.RegisterService(&_Syncer_serviceDesc, srv)
}

func _Syncer_GetBlocks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetBlocksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SyncerServer).GetBlocks(m, &syncerGetBlocksServer{stream})
}

type Syncer_GetBlocksServer interface {
	Send(*Block) error
	grpc.ServerStream
}

type syncerGetBlocksServer struct {
	grpc.ServerStream
}

func (x *syncerGetBlocksServer) Send(m *Block) error {
	return x.ServerStream.SendMsg(m)
}

func _Syncer_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncerServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Syncer/GetBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncerServer).GetBlock(ctx, req.(*GetBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Syncer_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncerServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Syncer/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncerServer).GetStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Syncer_NotifyStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Status)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncerServer).NotifyStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Syncer/NotifyStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncerServer).NotifyStatus(ctx, req.(*Status))
	}
	return interceptor(ctx, in, info, handler)
}

var _Syncer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Syncer",
	HandlerType: (*SyncerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlock",
			Handler:    _Syncer_GetBlock_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _Syncer_GetStatus_Handler,
		},
		{
			MethodName: "NotifyStatus",
			Handler:    _Syncer_NotifyStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetBlocks",
			Handler:       _Syncer_GetBlocks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "syncer/proto/syncer.proto",
}
