// Code generated by scapi/gen. DO NOT EDIT.
package contractsapi

import (
	"math/big"

	"github.com/0xPolygon/polygon-edge/types"
	"github.com/umbracle/ethgo"
	"github.com/umbracle/ethgo/abi"
)

var (
	_ = big.NewInt
	_ = types.Address{}
	_ = ethgo.Log{}
)

var (
	commitType = abi.MustNewMethod("function commit(tuple(uint256 startId,uint256 endId,uint256 leaves,bytes32 root) bundle,bytes signature,bytes bitmap)") //nolint:all
)

type Bundle struct {
	StartID *big.Int `abi:"startId"`
	EndID   *big.Int `abi:"endId"`
	Leaves  *big.Int `abi:"leaves"`
	Root    [32]byte `abi:"root"`
}

type Commit struct {
	Bundle    Bundle `abi:"bundle"`
	Signature []byte `abi:"signature"`
	Bitmap    []byte `abi:"bitmap"`
}

func (c *Commit) EncodeAbi() ([]byte, error) {
	return commitType.Encode(c)
}

func (c *Commit) DecodeAbi(buf []byte) error {
	return decodeMethod(commitType, buf, c)
}

var (
	commitEpochType = abi.MustNewMethod("function commitEpoch(uint256 id,tuple(uint256 startBlock,uint256 endBlock,bytes32 epochRoot) epoch,tuple(uint256 epochId,tuple(address validator,uint256 signedBlocks)[] uptimeData,uint256 totalBlocks) uptime)") //nolint:all
)

type Epoch struct {
	StartBlock *big.Int `abi:"startBlock"`
	EndBlock   *big.Int `abi:"endBlock"`
	EpochRoot  [32]byte `abi:"epochRoot"`
}

type UptimeData struct {
	Validator    types.Address `abi:"validator"`
	SignedBlocks *big.Int      `abi:"signedBlocks"`
}

type Uptime struct {
	EpochID     *big.Int     `abi:"epochId"`
	UptimeData  []UptimeData `abi:"uptimeData"`
	TotalBlocks *big.Int     `abi:"totalBlocks"`
}

type CommitEpoch struct {
	ID     *big.Int `abi:"id"`
	Epoch  Epoch    `abi:"epoch"`
	Uptime Uptime   `abi:"uptime"`
}

func (c *CommitEpoch) EncodeAbi() ([]byte, error) {
	return commitEpochType.Encode(c)
}

func (c *CommitEpoch) DecodeAbi(buf []byte) error {
	return decodeMethod(commitEpochType, buf, c)
}

var (
	StateSyncedEventType = abi.MustNewEvent("event StateSynced(uint256 indexed id,address indexed sender,address indexed receiver,bytes data)") //nolint:all
)

type StateSyncedEvent struct {
	ID       *big.Int      `abi:"id"`
	Sender   types.Address `abi:"sender"`
	Receiver types.Address `abi:"receiver"`
	Data     []byte        `abi:"data"`
}

func (S *StateSyncedEvent) ParseLog(log *ethgo.Log) error {
	return decodeEvent(StateSyncedEventType, log, S)
}
