// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IbftClient is the client API for Ibft service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IbftClient interface {
	Handshake(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*HandshakeResp, error)
	Message(ctx context.Context, in *MessageReq, opts ...grpc.CallOption) (*empty.Empty, error)
}

type ibftClient struct {
	cc grpc.ClientConnInterface
}

func NewIbftClient(cc grpc.ClientConnInterface) IbftClient {
	return &ibftClient{cc}
}

func (c *ibftClient) Handshake(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*HandshakeResp, error) {
	out := new(HandshakeResp)
	err := c.cc.Invoke(ctx, "/v1.Ibft/Handshake", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ibftClient) Message(ctx context.Context, in *MessageReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/v1.Ibft/Message", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IbftServer is the server API for Ibft service.
// All implementations must embed UnimplementedIbftServer
// for forward compatibility
type IbftServer interface {
	Handshake(context.Context, *empty.Empty) (*HandshakeResp, error)
	Message(context.Context, *MessageReq) (*empty.Empty, error)
	mustEmbedUnimplementedIbftServer()
}

// UnimplementedIbftServer must be embedded to have forward compatible implementations.
type UnimplementedIbftServer struct {
}

func (UnimplementedIbftServer) Handshake(context.Context, *empty.Empty) (*HandshakeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedIbftServer) Message(context.Context, *MessageReq) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Message not implemented")
}
func (UnimplementedIbftServer) mustEmbedUnimplementedIbftServer() {}

// UnsafeIbftServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IbftServer will
// result in compilation errors.
type UnsafeIbftServer interface {
	mustEmbedUnimplementedIbftServer()
}

func RegisterIbftServer(s grpc.ServiceRegistrar, srv IbftServer) {
	s.RegisterService(&Ibft_ServiceDesc, srv)
}

func _Ibft_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IbftServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Ibft/Handshake",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IbftServer).Handshake(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ibft_Message_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IbftServer).Message(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Ibft/Message",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IbftServer).Message(ctx, req.(*MessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Ibft_ServiceDesc is the grpc.ServiceDesc for Ibft service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ibft_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Ibft",
	HandlerType: (*IbftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _Ibft_Handshake_Handler,
		},
		{
			MethodName: "Message",
			Handler:    _Ibft_Message_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "consensus/ibft/proto/ibft.proto",
}
