// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IbftClient is the client API for Ibft service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IbftClient interface {
	Prepare(ctx context.Context, in *Subject, opts ...grpc.CallOption) (*empty.Empty, error)
	PrePrepare(ctx context.Context, in *Preprepare, opts ...grpc.CallOption) (*empty.Empty, error)
	Commit(ctx context.Context, in *Subject, opts ...grpc.CallOption) (*empty.Empty, error)
	RoundChange(ctx context.Context, in *Subject, opts ...grpc.CallOption) (*empty.Empty, error)
}

type ibftClient struct {
	cc grpc.ClientConnInterface
}

func NewIbftClient(cc grpc.ClientConnInterface) IbftClient {
	return &ibftClient{cc}
}

func (c *ibftClient) Prepare(ctx context.Context, in *Subject, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/v1.Ibft/Prepare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ibftClient) PrePrepare(ctx context.Context, in *Preprepare, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/v1.Ibft/PrePrepare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ibftClient) Commit(ctx context.Context, in *Subject, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/v1.Ibft/Commit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ibftClient) RoundChange(ctx context.Context, in *Subject, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/v1.Ibft/RoundChange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IbftServer is the server API for Ibft service.
// All implementations must embed UnimplementedIbftServer
// for forward compatibility
type IbftServer interface {
	Prepare(context.Context, *Subject) (*empty.Empty, error)
	PrePrepare(context.Context, *Preprepare) (*empty.Empty, error)
	Commit(context.Context, *Subject) (*empty.Empty, error)
	RoundChange(context.Context, *Subject) (*empty.Empty, error)
	mustEmbedUnimplementedIbftServer()
}

// UnimplementedIbftServer must be embedded to have forward compatible implementations.
type UnimplementedIbftServer struct {
}

func (UnimplementedIbftServer) Prepare(context.Context, *Subject) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prepare not implemented")
}
func (UnimplementedIbftServer) PrePrepare(context.Context, *Preprepare) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrePrepare not implemented")
}
func (UnimplementedIbftServer) Commit(context.Context, *Subject) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedIbftServer) RoundChange(context.Context, *Subject) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RoundChange not implemented")
}
func (UnimplementedIbftServer) mustEmbedUnimplementedIbftServer() {}

// UnsafeIbftServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IbftServer will
// result in compilation errors.
type UnsafeIbftServer interface {
	mustEmbedUnimplementedIbftServer()
}

func RegisterIbftServer(s grpc.ServiceRegistrar, srv IbftServer) {
	s.RegisterService(&Ibft_ServiceDesc, srv)
}

func _Ibft_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Subject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IbftServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Ibft/Prepare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IbftServer).Prepare(ctx, req.(*Subject))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ibft_PrePrepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Preprepare)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IbftServer).PrePrepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Ibft/PrePrepare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IbftServer).PrePrepare(ctx, req.(*Preprepare))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ibft_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Subject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IbftServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Ibft/Commit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IbftServer).Commit(ctx, req.(*Subject))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ibft_RoundChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Subject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IbftServer).RoundChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Ibft/RoundChange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IbftServer).RoundChange(ctx, req.(*Subject))
	}
	return interceptor(ctx, in, info, handler)
}

// Ibft_ServiceDesc is the grpc.ServiceDesc for Ibft service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ibft_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Ibft",
	HandlerType: (*IbftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Prepare",
			Handler:    _Ibft_Prepare_Handler,
		},
		{
			MethodName: "PrePrepare",
			Handler:    _Ibft_PrePrepare_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _Ibft_Commit_Handler,
		},
		{
			MethodName: "RoundChange",
			Handler:    _Ibft_RoundChange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "consensus/ibft/proto/ibft.proto",
}
