---
name: CLA Assistant
on: # yamllint disable-line rule:truthy
  issue_comment:
    types:
      - created
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  cla-assistant:
    runs-on: ubuntu-latest
    steps:
      - name: "Check CLA"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # the below token should have repo scope and must be manually added by you in the repository's secret
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: "cla.json"
          path-to-document: "https://github.com/Ethernal-Tech/blade/blob/develop/CLA.md"
          branch: "cla-signatures"
          allowlist: dependabot[bot],dependabot-preview[bot]
