---

name: Loadbot
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      runner:
        description: 'The runner to execute on'
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - devnet
          - testnet
      environment:
        description: 'The environment to run against'
        required: false
        type: environment
      chain_id:
        default: '750'
        description: The chain ID of the network to test
        type: string
      transaction_count:
        default: '10000'
        description: The number of transactions to send
        type: string
      transactions_per_second:
        default: '100'
        description: The amount of transactions per second to send
        type: string
      transaction_value:
        default: '100'
        description: The value per transactions to send
        type: string
  workflow_call:
    inputs:
      chain_id:
        description: The chain ID of the network to test
        type: string
      transaction_count:
        description: The number of transactions to send
        type: string
      transactions_per_second:
        description: The amount of transactions per second to send
        type: string
      transaction_value:
        description: The value per transactions to send
        type: string
      runner:
        required: true
        type: string
        description: The runner label to use
      environment:
        required: true
        description: 'The environment to run against'
        type: string
    secrets:
      SLACK_PERFORMANCE_WEBHOOK_URL:
        required: true
      LOADBOT_SENDER_ADDRESS:
        required: true
      LOADBOT_GRPC_ADDRESS:
        required: true
      LOADBOT_JSONRPC_URL:
        required: true
      LOADBOT_0x1AB8C3df809b85012a009c0264eb92dB04eD6EFa:
        required: true
jobs:
  run_loadbot:
    name: Run Loadbot
    concurrency: ${{ inputs.environment }}_performance
    environment: ${{ inputs.environment }}
    runs-on: ${{ inputs.runner  }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v3.3.0
        with:
          go-version: 1.18.x
      - name: Install JQ
        run: |
          mkdir -p $HOME/.local/bin
          curl -sLo $HOME/.local/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && chmod +x $HOME/.local/bin/jq
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - id: loadbot
        name: Run Loadbot
        continue-on-error: true
        run: |
          go run . loadbot --jsonrpc ${{ secrets.LOADBOT_JSONRPC_URL }} --grpc-address ${{ secrets.LOADBOT_GRPC_ADDRESS }} --sender ${{ secrets.LOADBOT_SENDER_ADDRESS }}  --count ${{ inputs.transaction_count}} --value ${{ inputs.transaction_value }} --tps ${{ inputs.transactions_per_second }} --chain-id ${{ inputs.chain_id }} --detailed --json > loadbotOutput.json
          cat loadbotOutput.json
          echo "::set-output name=tps::$(cat loadbotOutput.json | jq -r '.approx_tps')"
          echo "::set-output name=totalTx::$(cat loadbotOutput.json | jq -r '.count_data.total')"
          echo "::set-output name=failedTx::$(cat loadbotOutput.json | jq -r '.count_data.failed')"
        env:
          LOADBOT_0x1AB8C3df809b85012a009c0264eb92dB04eD6EFa: ${{ secrets.LOADBOT_0x1AB8C3df809b85012a009c0264eb92dB04eD6EFa }}
      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.22.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_PERFORMANCE_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Loadbot Results"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Approximate TPS: `${{ steps.loadbot.outputs.tps }}`"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Total Transactions: `${{ steps.loadbot.outputs.totalTx }}`"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Failed Transactions: `${{ steps.loadbot.outputs.failedTx }}`"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "context",
                  "elements": [
                      {
                        "type": "mrkdwn",
                        "text": "Environment: `${{ inputs.environment }}`"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "JSON-RPC Endpoint: ${{ secrets.LOADBOT_JSONRPC_URL }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "Workflow: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Results>"
                      }
                    ]
                  }
                ]
              }
