---
name: Property PolyBFT Tests
on: # yamllint disable-line rule:truthy
  # push:
  #   branches:
  #     - main
  #     - develop
  workflow_dispatch:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      workflow_output:
        description: "Property PolyBFT Tests output"
        value: ${{ jobs.polybft_property.outputs.property_output_failure }} 

jobs:
  polybft_property:
    name: Run Property PolyBFT Tests
    runs-on: ubuntu-latest
    env:
      E2E_TESTS: true
      E2E_LOGS: true
      CI_VERBOSE: true
    outputs:
      property_output_failure: ${{ steps.run_property_failure.outputs.test_output }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.20.x
      - name: Run tests
        run: make test-property-polybft
      - name: Run tests failed
        if: failure()
        id: run_property_failure
        run: echo "test_output=false" >> $GITHUB_OUTPUT
      - name: Archive test logs
        if: always()
        uses: actions/upload-artifact@v4.3.0
        with:
          name: e2e-logs
          path: e2e-logs-*/
          retention-days: 30
